In [1]:
#train
import numpy as np
from sklearn.multioutput import MultiOutputRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error
from sklearn.model_selection import GridSearchCV

In [2]:
X = np.load('np-array-h0.npy')
X

array([[297.3    , 297.71   , 297.59998, ..., 298.3    , 298.9    ,
        300.09998],
       [298.09998, 298.     , 298.21   , ..., 297.81   , 299.59998,
        301.5    ],
       [298.8    , 299.     , 299.21   , ..., 299.3    , 299.9    ,
        301.     ],
       ...,
       [298.9    , 299.1    , 299.3    , ..., 300.1    , 299.3    ,
        299.5    ],
       [299.6    , 300.2    , 300.2    , ..., 298.9    , 298.3    ,
        298.5    ],
       [300.4    , 300.4    , 300.2    , ..., 299.30002, 299.30002,
        300.1    ]], dtype=float32)

In [3]:
Y = np.load('np-array-h6.npy')
Y

array([[298.     , 298.3    , 298.09998, ..., 297.21   , 297.8    ,
        298.4    ],
       [298.     , 298.31   , 298.4    , ..., 296.71   , 297.59998,
        298.59998],
       [298.09998, 298.5    , 298.8    , ..., 298.7    , 299.2    ,
        300.09998],
       ...,
       [299.     , 299.80002, 300.     , ..., 298.1    , 297.6    ,
        297.5    ],
       [299.9    , 300.4    , 300.2    , ..., 297.1    , 296.9    ,
        297.1    ],
       [300.19998, 300.5    , 300.1    , ..., 296.69998, 297.     ,
        297.5    ]], dtype=float32)

In [63]:
X_test = np.load('np-array-h0-2023.npy')
X_test

array([[300.125 , 300.3125, 300.375 , ..., 298.    , 298.1875, 299.1875],
       [300.1875, 300.125 , 299.8125, ..., 297.1875, 297.6875, 299.1875],
       [299.5   , 299.125 , 299.3125, ..., 297.8125, 298.125 , 299.125 ],
       ...,
       [301.    , 300.3125, 300.875 , ..., 299.125 , 300.    , 300.8125],
       [301.125 , 300.875 , 301.3125, ..., 299.8125, 300.8125, 301.375 ],
       [301.125 , 300.8125, 301.125 , ..., 299.1875, 299.5   , 299.8125]],
      dtype=float32)

In [67]:
Y_test = np.load('np-array-h6-2023.npy')
Y_test

array([[300.5   , 301.1875, 301.    , ..., 297.3125, 297.3125, 297.6875],
       [299.8125, 299.875 , 299.375 , ..., 296.8125, 297.125 , 298.125 ],
       [298.875 , 299.1875, 299.125 , ..., 296.875 , 297.3125, 298.125 ],
       ...,
       [300.375 , 300.5   , 301.    , ..., 298.3125, 299.    , 299.1875],
       [300.875 , 301.    , 301.125 , ..., 297.5   , 298.1875, 298.875 ],
       [300.625 , 300.5   , 300.625 , ..., 299.    , 299.5   , 299.3125]],
      dtype=float32)

In [11]:
# Definir los hiperparámetros a ajustar
param_grid_DT = {
    'estimator__criterion': ['squared_error','friedman_mse', 'absolute_error', 'poisson'],
    'estimator__splitter': ['best', 'random'],
    'estimator__max_depth': [None,10, 20, 30],
    'estimator__min_samples_split':[2,4,6],
    'estimator__min_samples_leaf': [1,2,3],
}


In [12]:
# Crear el modelo
model = MultiOutputRegressor(DecisionTreeRegressor())
# Realizar GridSearchCV
grid_search = GridSearchCV(model, param_grid_DT, cv=5, scoring='neg_mean_absolute_error')
grid_search.fit(X, Y)

# Obtener los mejores hiperparámetros y el mejor modelo
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

In [13]:
best_params

{'estimator__criterion': 'squared_error',
 'estimator__max_depth': 10,
 'estimator__min_samples_leaf': 3,
 'estimator__min_samples_split': 4,
 'estimator__splitter': 'random'}